import pandas as pd
import re

# Load the config file
configfile: "config/config.yml"

# Load the sample sheet from the config file
samplesheet = pd.read_csv(config['samples_csv'], sep=r'[;,]', engine='python')
sample_ids = samplesheet['sample_id'].drop_duplicates().tolist()
sample_id_pattern = "|".join(re.escape(sid) for sid in sample_ids)

# Constrain sample_id wildcard to known sample IDs to avoid recursive expansion
wildcard_constraints:
    sample_id=sample_id_pattern

# Import rules
include: "modules/init.smk"
include: "modules/prepare_genome.smk"
include: "modules/common.smk"
include: "modules/qc.smk"
include: "modules/trim.smk"
include: "modules/align.smk"
include: "modules/mark_duplicates.smk"
include: "modules/align_stats.smk"
include: "modules/quant.smk"
include: "modules/fusion.smk"
include: "modules/stringtie.smk"
include: "modules/dupradar.smk"
include: "modules/rseqc.smk"
include: "modules/multiqc.smk"
include: "modules/delete_tmp.smk"

# Targets rule
rule all:
    input:
        get_target_files(sample_ids)
