import pandas as pd

# Load the config file
configfile: "config/config.yaml"

# Import rules
include: "modules/init.smk"
include: "modules/common.smk"
include: "modules/preprocess.smk"
include: "modules/align.smk"
include: "modules/qc.smk"

# Load the sample sheet from the config file
samplesheet = pd.read_csv(config['samples_csv'])
sample_ids = samplesheet['sample_id'].tolist()


# Add this rule to define the final target (all) for Snakemake
rule all:
    input:
        get_target_files(sample_ids)
