import pandas as pd

# Load the config file
configfile: "config/config.yaml"

# Import rules
include: "modules/init.smk"
include: "modules/common.smk"
include: "modules/qc.smk"
include: "modules/align.smk"
include: "modules/quant.smk"
include: "modules/fusion.smk"

# Load the sample sheet from the config file
samplesheet = pd.read_csv(config['samples_csv'], sep=r'[;,]', engine='python')
sample_ids = samplesheet['sample_id'].tolist()


# Targets rule
rule all:
    input:
        get_target_files(sample_ids)
