# Path or URL to the sample sheet (CSV format, columns: sample_id, outdir, fq1, fq2, replicate, condition, strandedness)
samples_csv: "~/nas4_home/expression_project/data/samplesheet_reduced.csv"

ref:
  assembly: "hg38"    # choices: hg19, hg38, chm13v2, m39

trimming:
  enabled: True

star_params:
  ffpe: >-
    --outSAMtype BAM SortedByCoordinate
    --genomeLoad LoadAndKeep
    --limitBAMsortRAM 10000000000
    --outFilterMultimapNmax 5
    --quantMode GeneCounts
  total_rna: >-
    --twopassMode Basic
    --genomeLoad NoSharedMemory
    --alignSJDBoverhangMin 3 
    --alignIntronMax 500000 
    --alignMatesGapMax 1000000 
    --sjdbScore 2 
    --outFilterMultimapNmax 5       
    --outFilterMultimapScoreRange 1 
    --outFilterMismatchNmax 3    
    --outFilterMatchNminOverLread 0.33 
    --outFilterScoreMinOverLread 0.33 
    --peOverlapNbasesMin 20
    --outSAMstrandField intronMotif

fastp_params:
  ffpe: >-
    --cut_front
    --cut_tail
    --cut_window_size 2
    --cut_mean_quality 20
    --length_required 50
  total_rna: >-
    --trim_front1 1
    --trim_front2 1
    --length_required 50
  other: >-


multiqc_cfg: "config/multiqc_config.yml"

stringtie:
  enabled: true

feature_counts:
  enabled: true
  group_type: "gene_biotype"

qualimap:
  enabled: true

dupradar:
  enabled: true

rseqc:
  bam_stat:
    enabled: true
  infer_experiment:
    enabled: true
  inner_distance:
    enabled: true
  read_distribution:
    enabled: true
  read_duplication:
    enabled: true
  read_GC:
    enabled: true
  junnction_annotation:
    enabled: true
  junction_saturation:
    enabled: true
